# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nicorivas/Software/BOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nicorivas/Software/BOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.1.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicorivas/Software/BOS/CMakeFiles /Users/nicorivas/Software/BOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nicorivas/Software/BOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bos

# Build rule for target.
bos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bos
.PHONY : bos

# fast build rule for target.
bos/fast:
	$(MAKE) -f CMakeFiles/bos.dir/build.make CMakeFiles/bos.dir/build
.PHONY : bos/fast

#=============================================================================
# Target rules for targets named GridUnitTest

# Build rule for target.
GridUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GridUnitTest
.PHONY : GridUnitTest

# fast build rule for target.
GridUnitTest/fast:
	$(MAKE) -f tests/CMakeFiles/GridUnitTest.dir/build.make tests/CMakeFiles/GridUnitTest.dir/build
.PHONY : GridUnitTest/fast

#=============================================================================
# Target rules for targets named IntersectionUnitTest

# Build rule for target.
IntersectionUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntersectionUnitTest
.PHONY : IntersectionUnitTest

# fast build rule for target.
IntersectionUnitTest/fast:
	$(MAKE) -f tests/CMakeFiles/IntersectionUnitTest.dir/build.make tests/CMakeFiles/IntersectionUnitTest.dir/build
.PHONY : IntersectionUnitTest/fast

#=============================================================================
# Target rules for targets named MathUnitTest

# Build rule for target.
MathUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MathUnitTest
.PHONY : MathUnitTest

# fast build rule for target.
MathUnitTest/fast:
	$(MAKE) -f tests/CMakeFiles/MathUnitTest.dir/build.make tests/CMakeFiles/MathUnitTest.dir/build
.PHONY : MathUnitTest/fast

#=============================================================================
# Target rules for targets named ModelElastic

# Build rule for target.
ModelElastic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModelElastic
.PHONY : ModelElastic

# fast build rule for target.
ModelElastic/fast:
	$(MAKE) -f tests/CMakeFiles/ModelElastic.dir/build.make tests/CMakeFiles/ModelElastic.dir/build
.PHONY : ModelElastic/fast

#=============================================================================
# Target rules for targets named ModelGravity

# Build rule for target.
ModelGravity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModelGravity
.PHONY : ModelGravity

# fast build rule for target.
ModelGravity/fast:
	$(MAKE) -f tests/CMakeFiles/ModelGravity.dir/build.make tests/CMakeFiles/ModelGravity.dir/build
.PHONY : ModelGravity/fast

#=============================================================================
# Target rules for targets named ModelInelastic

# Build rule for target.
ModelInelastic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModelInelastic
.PHONY : ModelInelastic

# fast build rule for target.
ModelInelastic/fast:
	$(MAKE) -f tests/CMakeFiles/ModelInelastic.dir/build.make tests/CMakeFiles/ModelInelastic.dir/build
.PHONY : ModelInelastic/fast

#=============================================================================
# Target rules for targets named PriorityQueue

# Build rule for target.
PriorityQueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PriorityQueue
.PHONY : PriorityQueue

# fast build rule for target.
PriorityQueue/fast:
	$(MAKE) -f tests/CMakeFiles/PriorityQueue.dir/build.make tests/CMakeFiles/PriorityQueue.dir/build
.PHONY : PriorityQueue/fast

#=============================================================================
# Target rules for targets named SimulationUnitTest

# Build rule for target.
SimulationUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimulationUnitTest
.PHONY : SimulationUnitTest

# fast build rule for target.
SimulationUnitTest/fast:
	$(MAKE) -f tests/CMakeFiles/SimulationUnitTest.dir/build.make tests/CMakeFiles/SimulationUnitTest.dir/build
.PHONY : SimulationUnitTest/fast

bos.o: bos.cpp.o
.PHONY : bos.o

# target to build an object file
bos.cpp.o:
	$(MAKE) -f CMakeFiles/bos.dir/build.make CMakeFiles/bos.dir/bos.cpp.o
.PHONY : bos.cpp.o

bos.i: bos.cpp.i
.PHONY : bos.i

# target to preprocess a source file
bos.cpp.i:
	$(MAKE) -f CMakeFiles/bos.dir/build.make CMakeFiles/bos.dir/bos.cpp.i
.PHONY : bos.cpp.i

bos.s: bos.cpp.s
.PHONY : bos.s

# target to generate assembly for a file
bos.cpp.s:
	$(MAKE) -f CMakeFiles/bos.dir/build.make CMakeFiles/bos.dir/bos.cpp.s
.PHONY : bos.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bos"
	@echo "... test"
	@echo "... IntersectionUnitTest"
	@echo "... PriorityQueue"
	@echo "... GridUnitTest"
	@echo "... ModelGravity"
	@echo "... SimulationUnitTest"
	@echo "... ModelElastic"
	@echo "... MathUnitTest"
	@echo "... ModelInelastic"
	@echo "... bos.o"
	@echo "... bos.i"
	@echo "... bos.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

